version: '2'
services:
  web:
    build: .
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.9
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./app:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    links:
     - db

  db:
    image: mysql
    ports:
     - "3306:3306"
    volumes:
     - ./dbdata:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: "root" 
     MYSQL_DATABASE: "main"    